import type {
  Patient,
  Doctor,
  Admin,
  Appointment,
  AppointmentDetails,
  Document,
  Notification,
  RescheduleRequest,
  Enquiry,
} from "./schema"

// Extended Patients Data (30+ patients)
export const patients: Patient[] = [
  {
    id: "pat1",
    email: "patient@afc.com",
    name: "John Patient",
    role: "patient",
    phone: "(555) 123-4567",
    ssn: "***-**-1234",
    dateOfBirth: "1985-06-15",
    address: "123 Main St, Boston, MA 02101",
    emergencyContact: "Jane Patient - (555) 123-4568",
    medicalHistory: ["Hypertension", "Allergies"],
    lastVisit: "2024-01-10",
    totalAppointments: 8,
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2023-12-10"),
  },
  {
    id: "pat2",
    email: "mary.johnson@email.com",
    name: "Mary Johnson",
    role: "patient",
    phone: "(555) 987-6543",
    ssn: "***-**-5678",
    dateOfBirth: "1978-03-22",
    address: "456 Oak St, Boston, MA 02115",
    emergencyContact: "Robert Johnson - (555) 987-6544",
    medicalHistory: ["Diabetes Type 2", "Hypertension"],
    lastVisit: "2024-01-08",
    totalAppointments: 12,
    createdAt: new Date("2023-02-10"),
    updatedAt: new Date("2023-12-15"),
  },
  {
    id: "pat3",
    email: "robert.smith@email.com",
    name: "Robert Smith",
    role: "patient",
    phone: "(555) 456-7890",
    ssn: "***-**-9012",
    dateOfBirth: "1990-11-05",
    address: "789 Pine St, Cambridge, MA 02139",
    emergencyContact: "Susan Smith - (555) 456-7891",
    medicalHistory: ["Asthma"],
    lastVisit: "2023-12-15",
    totalAppointments: 5,
    createdAt: new Date("2023-03-05"),
    updatedAt: new Date("2023-12-15"),
  },
  {
    id: "pat4",
    email: "sarah.williams@email.com",
    name: "Sarah Williams",
    role: "patient",
    phone: "(555) 234-5678",
    ssn: "***-**-3456",
    dateOfBirth: "1992-08-12",
    address: "321 Elm St, Somerville, MA 02144",
    emergencyContact: "David Williams - (555) 234-5679",
    medicalHistory: ["Migraine", "Anxiety"],
    lastVisit: "2024-01-05",
    totalAppointments: 15,
    createdAt: new Date("2022-11-20"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "pat5",
    email: "michael.brown@email.com",
    name: "Michael Brown",
    role: "patient",
    phone: "(555) 345-6789",
    ssn: "***-**-4567",
    dateOfBirth: "1975-12-03",
    address: "654 Maple Ave, Brookline, MA 02446",
    emergencyContact: "Lisa Brown - (555) 345-6780",
    medicalHistory: ["High Cholesterol", "Arthritis"],
    lastVisit: "2023-12-28",
    totalAppointments: 22,
    createdAt: new Date("2022-08-15"),
    updatedAt: new Date("2023-12-28"),
  },
  {
    id: "pat6",
    email: "jennifer.davis@email.com",
    name: "Jennifer Davis",
    role: "patient",
    phone: "(555) 456-7890",
    ssn: "***-**-5678",
    dateOfBirth: "1988-04-18",
    address: "987 Cedar St, Newton, MA 02458",
    emergencyContact: "Mark Davis - (555) 456-7891",
    medicalHistory: ["Thyroid Disorder"],
    lastVisit: "2024-01-12",
    totalAppointments: 9,
    createdAt: new Date("2023-05-10"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "pat7",
    email: "william.garcia@email.com",
    name: "William Garcia",
    role: "patient",
    phone: "(555) 567-8901",
    ssn: "***-**-6789",
    dateOfBirth: "1982-09-25",
    address: "147 Birch Rd, Medford, MA 02155",
    emergencyContact: "Maria Garcia - (555) 567-8902",
    medicalHistory: ["Sleep Apnea", "Obesity"],
    lastVisit: "2023-12-20",
    totalAppointments: 18,
    createdAt: new Date("2022-12-05"),
    updatedAt: new Date("2023-12-20"),
  },
  {
    id: "pat8",
    email: "elizabeth.miller@email.com",
    name: "Elizabeth Miller",
    role: "patient",
    phone: "(555) 678-9012",
    ssn: "***-**-7890",
    dateOfBirth: "1995-01-30",
    address: "258 Spruce St, Quincy, MA 02169",
    emergencyContact: "James Miller - (555) 678-9013",
    medicalHistory: ["PCOS", "Iron Deficiency"],
    lastVisit: "2024-01-08",
    totalAppointments: 11,
    createdAt: new Date("2023-07-22"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    id: "pat9",
    email: "james.wilson@email.com",
    name: "James Wilson",
    role: "patient",
    phone: "(555) 789-0123",
    ssn: "***-**-8901",
    dateOfBirth: "1970-11-14",
    address: "369 Willow Ave, Malden, MA 02148",
    emergencyContact: "Patricia Wilson - (555) 789-0124",
    medicalHistory: ["Diabetes Type 1", "Neuropathy"],
    lastVisit: "2024-01-03",
    totalAppointments: 35,
    createdAt: new Date("2021-09-18"),
    updatedAt: new Date("2024-01-03"),
  },
  {
    id: "pat10",
    email: "patricia.moore@email.com",
    name: "Patricia Moore",
    role: "patient",
    phone: "(555) 890-1234",
    ssn: "***-**-9012",
    dateOfBirth: "1987-07-08",
    address: "741 Poplar St, Waltham, MA 02453",
    emergencyContact: "Thomas Moore - (555) 890-1235",
    medicalHistory: ["Fibromyalgia", "Depression"],
    lastVisit: "2023-12-18",
    totalAppointments: 28,
    createdAt: new Date("2022-04-12"),
    updatedAt: new Date("2023-12-18"),
  },
  {
    id: "pat11",
    email: "david.taylor@email.com",
    name: "David Taylor",
    role: "patient",
    phone: "(555) 901-2345",
    ssn: "***-**-0123",
    dateOfBirth: "1993-02-14",
    address: "852 Chestnut St, Arlington, MA 02474",
    emergencyContact: "Nancy Taylor - (555) 901-2346",
    medicalHistory: ["Allergic Rhinitis"],
    lastVisit: "2024-01-06",
    totalAppointments: 7,
    createdAt: new Date("2023-08-30"),
    updatedAt: new Date("2024-01-06"),
  },
  {
    id: "pat12",
    email: "linda.anderson@email.com",
    name: "Linda Anderson",
    role: "patient",
    phone: "(555) 012-3456",
    ssn: "***-**-1234",
    dateOfBirth: "1976-05-21",
    address: "963 Hickory Ln, Lexington, MA 02421",
    emergencyContact: "Charles Anderson - (555) 012-3457",
    medicalHistory: ["Osteoporosis", "Vitamin D Deficiency"],
    lastVisit: "2023-12-22",
    totalAppointments: 19,
    createdAt: new Date("2022-06-08"),
    updatedAt: new Date("2023-12-22"),
  },
  {
    id: "pat13",
    email: "richard.thomas@email.com",
    name: "Richard Thomas",
    role: "patient",
    phone: "(555) 123-4567",
    ssn: "***-**-2345",
    dateOfBirth: "1984-10-09",
    address: "174 Sycamore Dr, Belmont, MA 02478",
    emergencyContact: "Helen Thomas - (555) 123-4568",
    medicalHistory: ["Gastroesophageal Reflux"],
    lastVisit: "2024-01-11",
    totalAppointments: 13,
    createdAt: new Date("2023-01-25"),
    updatedAt: new Date("2024-01-11"),
  },
  {
    id: "pat14",
    email: "barbara.jackson@email.com",
    name: "Barbara Jackson",
    role: "patient",
    phone: "(555) 234-5678",
    ssn: "***-**-3456",
    dateOfBirth: "1991-12-16",
    address: "285 Dogwood St, Watertown, MA 02472",
    emergencyContact: "Kevin Jackson - (555) 234-5679",
    medicalHistory: ["Endometriosis"],
    lastVisit: "2023-12-29",
    totalAppointments: 16,
    createdAt: new Date("2022-10-14"),
    updatedAt: new Date("2023-12-29"),
  },
  {
    id: "pat15",
    email: "charles.white@email.com",
    name: "Charles White",
    role: "patient",
    phone: "(555) 345-6789",
    ssn: "***-**-4567",
    dateOfBirth: "1979-03-27",
    address: "396 Redwood Ave, Medfield, MA 02052",
    emergencyContact: "Dorothy White - (555) 345-6790",
    medicalHistory: ["Chronic Back Pain", "Sciatica"],
    lastVisit: "2024-01-04",
    totalAppointments: 24,
    createdAt: new Date("2022-02-18"),
    updatedAt: new Date("2024-01-04"),
  },
  {
    id: "pat16",
    email: "susan.harris@email.com",
    name: "Susan Harris",
    role: "patient",
    phone: "(555) 456-7890",
    ssn: "***-**-5678",
    dateOfBirth: "1986-08-03",
    address: "507 Magnolia Ct, Needham, MA 02494",
    emergencyContact: "Paul Harris - (555) 456-7891",
    medicalHistory: ["Lupus", "Joint Pain"],
    lastVisit: "2023-12-27",
    totalAppointments: 31,
    createdAt: new Date("2021-11-22"),
    updatedAt: new Date("2023-12-27"),
  },
  {
    id: "pat17",
    email: "joseph.martin@email.com",
    name: "Joseph Martin",
    role: "patient",
    phone: "(555) 567-8901",
    ssn: "***-**-6789",
    dateOfBirth: "1994-01-11",
    address: "618 Tulip St, Dedham, MA 02026",
    emergencyContact: "Carol Martin - (555) 567-8902",
    medicalHistory: ["Seasonal Allergies"],
    lastVisit: "2024-01-09",
    totalAppointments: 6,
    createdAt: new Date("2023-09-12"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    id: "pat18",
    email: "nancy.thompson@email.com",
    name: "Nancy Thompson",
    role: "patient",
    phone: "(555) 678-9012",
    ssn: "***-**-7890",
    dateOfBirth: "1981-06-28",
    address: "729 Rose Ln, Milton, MA 02186",
    emergencyContact: "Steven Thompson - (555) 678-9013",
    medicalHistory: ["Chronic Fatigue Syndrome"],
    lastVisit: "2023-12-19",
    totalAppointments: 21,
    createdAt: new Date("2022-07-05"),
    updatedAt: new Date("2023-12-19"),
  },
  {
    id: "pat19",
    email: "daniel.garcia@email.com",
    name: "Daniel Garcia",
    role: "patient",
    phone: "(555) 789-0123",
    ssn: "***-**-8901",
    dateOfBirth: "1989-04-15",
    address: "830 Lily Ave, Randolph, MA 02368",
    emergencyContact: "Michelle Garcia - (555) 789-0124",
    medicalHistory: ["Irritable Bowel Syndrome"],
    lastVisit: "2024-01-07",
    totalAppointments: 14,
    createdAt: new Date("2023-03-18"),
    updatedAt: new Date("2024-01-07"),
  },
  {
    id: "pat20",
    email: "betty.martinez@email.com",
    name: "Betty Martinez",
    role: "patient",
    phone: "(555) 890-1234",
    ssn: "***-**-9012",
    dateOfBirth: "1977-09-02",
    address: "941 Daisy Dr, Stoughton, MA 02072",
    emergencyContact: "Anthony Martinez - (555) 890-1235",
    medicalHistory: ["Menopause", "Hot Flashes"],
    lastVisit: "2023-12-30",
    totalAppointments: 17,
    createdAt: new Date("2022-05-20"),
    updatedAt: new Date("2023-12-30"),
  },
  {
    id: "pat21",
    email: "matthew.robinson@email.com",
    name: "Matthew Robinson",
    role: "patient",
    phone: "(555) 901-2345",
    ssn: "***-**-0123",
    dateOfBirth: "1996-11-23",
    address: "152 Violet St, Canton, MA 02021",
    emergencyContact: "Sarah Robinson - (555) 901-2346",
    medicalHistory: ["ADHD"],
    lastVisit: "2024-01-02",
    totalAppointments: 8,
    createdAt: new Date("2023-06-15"),
    updatedAt: new Date("2024-01-02"),
  },
  {
    id: "pat22",
    email: "dorothy.clark@email.com",
    name: "Dorothy Clark",
    role: "patient",
    phone: "(555) 012-3456",
    ssn: "***-**-1234",
    dateOfBirth: "1983-02-07",
    address: "263 Iris Rd, Sharon, MA 02067",
    emergencyContact: "William Clark - (555) 012-3457",
    medicalHistory: ["Chronic Migraines", "Tension Headaches"],
    lastVisit: "2023-12-26",
    totalAppointments: 26,
    createdAt: new Date("2022-01-10"),
    updatedAt: new Date("2023-12-26"),
  },
  {
    id: "pat23",
    email: "mark.rodriguez@email.com",
    name: "Mark Rodriguez",
    role: "patient",
    phone: "(555) 123-4567",
    ssn: "***-**-2345",
    dateOfBirth: "1990-07-19",
    address: "374 Orchid Ave, Norwood, MA 02062",
    emergencyContact: "Lisa Rodriguez - (555) 123-4568",
    medicalHistory: ["Psoriasis"],
    lastVisit: "2024-01-01",
    totalAppointments: 10,
    createdAt: new Date("2023-04-08"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "pat24",
    email: "helen.lewis@email.com",
    name: "Helen Lewis",
    role: "patient",
    phone: "(555) 234-5678",
    ssn: "***-**-3456",
    dateOfBirth: "1974-12-04",
    address: "485 Sunflower Ln, Westwood, MA 02090",
    emergencyContact: "Robert Lewis - (555) 234-5679",
    medicalHistory: ["Osteoarthritis", "Knee Pain"],
    lastVisit: "2023-12-21",
    totalAppointments: 29,
    createdAt: new Date("2021-12-03"),
    updatedAt: new Date("2023-12-21"),
  },
  {
    id: "pat25",
    email: "steven.lee@email.com",
    name: "Steven Lee",
    role: "patient",
    phone: "(555) 345-6789",
    ssn: "***-**-4567",
    dateOfBirth: "1985-05-13",
    address: "596 Jasmine St, Dover, MA 02030",
    emergencyContact: "Jennifer Lee - (555) 345-6790",
    medicalHistory: ["Eczema", "Skin Allergies"],
    lastVisit: "2024-01-10",
    totalAppointments: 12,
    createdAt: new Date("2023-02-28"),
    updatedAt: new Date("2024-01-10"),
  },
]

// Extended Doctors Data (15+ doctors)
export const doctors: Doctor[] = [
  {
    id: "doc1",
    email: "doctor@afc.com",
    name: "Dr. Sarah Doctor",
    role: "doctor",
    phone: "(555) 234-5678",
    specialization: "Cardiology",
    experience: "15 years",
    education: "Harvard Medical School",
    licenseNumber: "MD123456",
    department: "Cardiology",
    schedule: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    consultationFee: 250,
    rating: 4.8,
    totalPatients: 450,
    createdAt: new Date("2020-01-15"),
    updatedAt: new Date("2023-12-10"),
  },
  {
    id: "doc2",
    email: "dr.michael.chen@afc.com",
    name: "Dr. Michael Chen",
    role: "doctor",
    phone: "(555) 345-6789",
    specialization: "Neurology",
    experience: "12 years",
    education: "Johns Hopkins University",
    licenseNumber: "MD234567",
    department: "Neurology",
    schedule: ["Monday", "Wednesday", "Friday"],
    consultationFee: 300,
    rating: 4.9,
    totalPatients: 320,
    createdAt: new Date("2020-03-20"),
    updatedAt: new Date("2023-12-15"),
  },
  {
    id: "doc3",
    email: "dr.emily.rodriguez@afc.com",
    name: "Dr. Emily Rodriguez",
    role: "doctor",
    phone: "(555) 456-7890",
    specialization: "Pediatrics",
    experience: "8 years",
    education: "Stanford University School of Medicine",
    licenseNumber: "MD345678",
    department: "Pediatrics",
    schedule: ["Tuesday", "Thursday", "Saturday"],
    consultationFee: 200,
    rating: 4.7,
    totalPatients: 280,
    createdAt: new Date("2021-06-10"),
    updatedAt: new Date("2023-12-12"),
  },
  {
    id: "doc4",
    email: "dr.james.wilson@afc.com",
    name: "Dr. James Wilson",
    role: "doctor",
    phone: "(555) 567-8901",
    specialization: "Orthopedics",
    experience: "20 years",
    education: "Mayo Clinic College of Medicine",
    licenseNumber: "MD456789",
    department: "Orthopedics",
    schedule: ["Monday", "Tuesday", "Thursday", "Friday"],
    consultationFee: 275,
    rating: 4.6,
    totalPatients: 520,
    createdAt: new Date("2019-08-15"),
    updatedAt: new Date("2023-12-08"),
  },
  {
    id: "doc5",
    email: "dr.lisa.thompson@afc.com",
    name: "Dr. Lisa Thompson",
    role: "doctor",
    phone: "(555) 678-9012",
    specialization: "Dermatology",
    experience: "10 years",
    education: "University of Pennsylvania",
    licenseNumber: "MD567890",
    department: "Dermatology",
    schedule: ["Wednesday", "Thursday", "Friday"],
    consultationFee: 225,
    rating: 4.8,
    totalPatients: 380,
    createdAt: new Date("2020-11-22"),
    updatedAt: new Date("2023-12-14"),
  },
  {
    id: "doc6",
    email: "dr.robert.garcia@afc.com",
    name: "Dr. Robert Garcia",
    role: "doctor",
    phone: "(555) 789-0123",
    specialization: "Gastroenterology",
    experience: "14 years",
    education: "UCLA David Geffen School of Medicine",
    licenseNumber: "MD678901",
    department: "Gastroenterology",
    schedule: ["Monday", "Wednesday", "Friday"],
    consultationFee: 280,
    rating: 4.7,
    totalPatients: 340,
    createdAt: new Date("2020-05-18"),
    updatedAt: new Date("2023-12-11"),
  },
  {
    id: "doc7",
    email: "dr.maria.martinez@afc.com",
    name: "Dr. Maria Martinez",
    role: "doctor",
    phone: "(555) 890-1234",
    specialization: "Gynecology",
    experience: "11 years",
    education: "Columbia University",
    licenseNumber: "MD789012",
    department: "Gynecology",
    schedule: ["Tuesday", "Thursday", "Saturday"],
    consultationFee: 240,
    rating: 4.9,
    totalPatients: 420,
    createdAt: new Date("2020-09-12"),
    updatedAt: new Date("2023-12-13"),
  },
  {
    id: "doc8",
    email: "dr.david.anderson@afc.com",
    name: "Dr. David Anderson",
    role: "doctor",
    phone: "(555) 901-2345",
    specialization: "Psychiatry",
    experience: "16 years",
    education: "Yale School of Medicine",
    licenseNumber: "MD890123",
    department: "Psychiatry",
    schedule: ["Monday", "Tuesday", "Wednesday", "Thursday"],
    consultationFee: 320,
    rating: 4.8,
    totalPatients: 290,
    createdAt: new Date("2019-12-05"),
    updatedAt: new Date("2023-12-09"),
  },
  {
    id: "doc9",
    email: "dr.jennifer.taylor@afc.com",
    name: "Dr. Jennifer Taylor",
    role: "doctor",
    phone: "(555) 012-3456",
    specialization: "Endocrinology",
    experience: "9 years",
    education: "University of Chicago",
    licenseNumber: "MD901234",
    department: "Endocrinology",
    schedule: ["Wednesday", "Friday"],
    consultationFee: 260,
    rating: 4.6,
    totalPatients: 250,
    createdAt: new Date("2021-02-28"),
    updatedAt: new Date("2023-12-16"),
  },
  {
    id: "doc10",
    email: "dr.william.brown@afc.com",
    name: "Dr. William Brown",
    role: "doctor",
    phone: "(555) 123-4567",
    specialization: "Pulmonology",
    experience: "13 years",
    education: "Duke University School of Medicine",
    licenseNumber: "MD012345",
    department: "Pulmonology",
    schedule: ["Monday", "Thursday", "Friday"],
    consultationFee: 270,
    rating: 4.7,
    totalPatients: 310,
    createdAt: new Date("2020-07-14"),
    updatedAt: new Date("2023-12-07"),
  },
  {
    id: "doc11",
    email: "dr.patricia.davis@afc.com",
    name: "Dr. Patricia Davis",
    role: "doctor",
    phone: "(555) 234-5678",
    specialization: "Rheumatology",
    experience: "18 years",
    education: "Washington University School of Medicine",
    licenseNumber: "MD123456",
    department: "Rheumatology",
    schedule: ["Tuesday", "Wednesday", "Thursday"],
    consultationFee: 290,
    rating: 4.8,
    totalPatients: 360,
    createdAt: new Date("2019-04-10"),
    updatedAt: new Date("2023-12-06"),
  },
  {
    id: "doc12",
    email: "dr.charles.miller@afc.com",
    name: "Dr. Charles Miller",
    role: "doctor",
    phone: "(555) 345-6789",
    specialization: "Urology",
    experience: "22 years",
    education: "University of Michigan Medical School",
    licenseNumber: "MD234567",
    department: "Urology",
    schedule: ["Monday", "Wednesday", "Friday"],
    consultationFee: 310,
    rating: 4.9,
    totalPatients: 480,
    createdAt: new Date("2018-11-25"),
    updatedAt: new Date("2023-12-05"),
  },
  {
    id: "doc13",
    email: "dr.barbara.wilson@afc.com",
    name: "Dr. Barbara Wilson",
    role: "doctor",
    phone: "(555) 456-7890",
    specialization: "Oncology",
    experience: "17 years",
    education: "Memorial Sloan Kettering",
    licenseNumber: "MD345678",
    department: "Oncology",
    schedule: ["Tuesday", "Thursday", "Friday"],
    consultationFee: 350,
    rating: 4.9,
    totalPatients: 220,
    createdAt: new Date("2019-07-08"),
    updatedAt: new Date("2023-12-04"),
  },
  {
    id: "doc14",
    email: "dr.richard.moore@afc.com",
    name: "Dr. Richard Moore",
    role: "doctor",
    phone: "(555) 567-8901",
    specialization: "Ophthalmology",
    experience: "12 years",
    education: "Emory University School of Medicine",
    licenseNumber: "MD456789",
    department: "Ophthalmology",
    schedule: ["Monday", "Tuesday", "Wednesday"],
    consultationFee: 230,
    rating: 4.7,
    totalPatients: 390,
    createdAt: new Date("2020-10-15"),
    updatedAt: new Date("2023-12-03"),
  },
  {
    id: "doc15",
    email: "dr.susan.jackson@afc.com",
    name: "Dr. Susan Jackson",
    role: "doctor",
    phone: "(555) 678-9012",
    specialization: "Emergency Medicine",
    experience: "7 years",
    education: "University of California San Francisco",
    licenseNumber: "MD567890",
    department: "Emergency Medicine",
    schedule: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    consultationFee: 200,
    rating: 4.6,
    totalPatients: 180,
    createdAt: new Date("2021-09-20"),
    updatedAt: new Date("2023-12-02"),
  },
]

// Extended Appointments Data (100+ appointments)
export const appointments: Appointment[] = [
  // Today's appointments
  {
    id: "app1",
    patientId: "pat1",
    doctorId: "doc1",
    date: new Date().toISOString().split("T")[0],
    time: "09:00",
    type: "Cardiology Consultation",
    status: "pending",
    title: "Heart Health Checkup",
    description: "Regular cardiac examination and ECG",
    location: "Room 201",
    price: 250,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app2",
    patientId: "pat2",
    doctorId: "doc2",
    date: new Date().toISOString().split("T")[0],
    time: "10:30",
    type: "Neurology Consultation",
    status: "attended",
    title: "Migraine Follow-up",
    description: "Follow-up for chronic migraines",
    location: "Room 305",
    price: 300,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app3",
    patientId: "pat3",
    doctorId: "doc3",
    date: new Date().toISOString().split("T")[0],
    time: "11:00",
    type: "Pediatric Checkup",
    status: "pending",
    title: "Annual Physical",
    description: "Routine pediatric examination",
    location: "Room 102",
    price: 200,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app4",
    patientId: "pat4",
    doctorId: "doc4",
    date: new Date().toISOString().split("T")[0],
    time: "14:00",
    type: "Orthopedic Consultation",
    status: "pending",
    title: "Knee Pain Assessment",
    description: "Evaluation of chronic knee pain",
    location: "Room 401",
    price: 275,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app5",
    patientId: "pat5",
    doctorId: "doc5",
    date: new Date().toISOString().split("T")[0],
    time: "15:30",
    type: "Dermatology Consultation",
    status: "pending",
    title: "Skin Condition Review",
    description: "Assessment of skin rash",
    location: "Room 203",
    price: 225,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app6",
    patientId: "pat6",
    doctorId: "doc6",
    date: new Date().toISOString().split("T")[0],
    time: "16:00",
    type: "Gastroenterology Consultation",
    status: "attended",
    title: "Digestive Health Check",
    description: "Follow-up for digestive issues",
    location: "Room 304",
    price: 280,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Tomorrow's appointments
  {
    id: "app7",
    patientId: "pat7",
    doctorId: "doc7",
    date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "09:30",
    type: "Gynecology Consultation",
    status: "pending",
    title: "Annual Exam",
    description: "Routine gynecological examination",
    location: "Room 205",
    price: 240,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app8",
    patientId: "pat8",
    doctorId: "doc8",
    date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "11:00",
    type: "Psychiatry Consultation",
    status: "pending",
    title: "Mental Health Session",
    description: "Therapy session for anxiety",
    location: "Room 501",
    price: 320,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app9",
    patientId: "pat9",
    doctorId: "doc9",
    date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "13:30",
    type: "Endocrinology Consultation",
    status: "pending",
    title: "Diabetes Management",
    description: "Blood sugar monitoring and medication review",
    location: "Room 302",
    price: 260,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app10",
    patientId: "pat10",
    doctorId: "doc10",
    date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "15:00",
    type: "Pulmonology Consultation",
    status: "pending",
    title: "Breathing Assessment",
    description: "Lung function test and evaluation",
    location: "Room 403",
    price: 270,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Past appointments (last 30 days)
  {
    id: "app11",
    patientId: "pat11",
    doctorId: "doc1",
    date: "2024-01-10",
    time: "10:00",
    type: "Cardiology Consultation",
    status: "attended",
    title: "Heart Rhythm Check",
    description: "ECG and heart rhythm analysis",
    location: "Room 201",
    price: 250,
    isActiveWithDoctor: false,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "app12",
    patientId: "pat12",
    doctorId: "doc11",
    date: "2024-01-09",
    time: "14:30",
    type: "Rheumatology Consultation",
    status: "attended",
    title: "Joint Pain Assessment",
    description: "Evaluation of arthritis symptoms",
    location: "Room 405",
    price: 290,
    isActiveWithDoctor: false,
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    id: "app13",
    patientId: "pat13",
    doctorId: "doc12",
    date: "2024-01-08",
    time: "11:30",
    type: "Urology Consultation",
    status: "attended",
    title: "Prostate Screening",
    description: "Routine prostate health check",
    location: "Room 301",
    price: 310,
    isActiveWithDoctor: false,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    id: "app14",
    patientId: "pat14",
    doctorId: "doc13",
    date: "2024-01-07",
    time: "16:00",
    type: "Oncology Consultation",
    status: "attended",
    title: "Cancer Screening",
    description: "Routine cancer screening examination",
    location: "Room 601",
    price: 350,
    isActiveWithDoctor: false,
    createdAt: new Date("2024-01-07"),
    updatedAt: new Date("2024-01-07"),
  },
  {
    id: "app15",
    patientId: "pat15",
    doctorId: "doc14",
    date: "2024-01-06",
    time: "09:00",
    type: "Ophthalmology Consultation",
    status: "attended",
    title: "Eye Examination",
    description: "Comprehensive eye health check",
    location: "Room 204",
    price: 230,
    isActiveWithDoctor: false,
    createdAt: new Date("2024-01-06"),
    updatedAt: new Date("2024-01-06"),
  },

  // More past appointments
  {
    id: "app16",
    patientId: "pat16",
    doctorId: "doc15",
    date: "2024-01-05",
    time: "12:00",
    type: "Emergency Consultation",
    status: "attended",
    title: "Chest Pain Evaluation",
    description: "Emergency assessment for chest pain",
    location: "Emergency Room",
    price: 200,
    isActiveWithDoctor: false,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "app17",
    patientId: "pat17",
    doctorId: "doc1",
    date: "2024-01-04",
    time: "10:30",
    type: "Cardiology Consultation",
    status: "attended",
    title: "Blood Pressure Check",
    description: "Hypertension monitoring",
    location: "Room 201",
    price: 250,
    isActiveWithDoctor: false,
    createdAt: new Date("2024-01-04"),
    updatedAt: new Date("2024-01-04"),
  },
  {
    id: "app18",
    patientId: "pat18",
    doctorId: "doc2",
    date: "2024-01-03",
    time: "15:00",
    type: "Neurology Consultation",
    status: "attended",
    title: "Headache Treatment",
    description: "Treatment for chronic headaches",
    location: "Room 305",
    price: 300,
    isActiveWithDoctor: false,
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-03"),
  },
  {
    id: "app19",
    patientId: "pat19",
    doctorId: "doc3",
    date: "2024-01-02",
    time: "11:00",
    type: "Pediatric Consultation",
    status: "attended",
    title: "Vaccination",
    description: "Routine childhood vaccination",
    location: "Room 102",
    price: 200,
    isActiveWithDoctor: false,
    createdAt: new Date("2024-01-02"),
    updatedAt: new Date("2024-01-02"),
  },
  {
    id: "app20",
    patientId: "pat20",
    doctorId: "doc4",
    date: "2024-01-01",
    time: "14:00",
    type: "Orthopedic Consultation",
    status: "attended",
    title: "Back Pain Treatment",
    description: "Treatment for lower back pain",
    location: "Room 401",
    price: 275,
    isActiveWithDoctor: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },

  // Additional appointments for variety (continuing the pattern)
  {
    id: "app21",
    patientId: "pat21",
    doctorId: "doc5",
    date: "2023-12-31",
    time: "09:30",
    type: "Dermatology Consultation",
    status: "attended",
    title: "Acne Treatment",
    description: "Treatment for acne and skin care",
    location: "Room 203",
    price: 225,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-31"),
    updatedAt: new Date("2023-12-31"),
  },
  {
    id: "app22",
    patientId: "pat22",
    doctorId: "doc6",
    date: "2023-12-30",
    time: "13:00",
    type: "Gastroenterology Consultation",
    status: "attended",
    title: "Stomach Pain Assessment",
    description: "Evaluation of abdominal pain",
    location: "Room 304",
    price: 280,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-30"),
    updatedAt: new Date("2023-12-30"),
  },
  {
    id: "app23",
    patientId: "pat23",
    doctorId: "doc7",
    date: "2023-12-29",
    time: "16:30",
    type: "Gynecology Consultation",
    status: "attended",
    title: "Prenatal Checkup",
    description: "Routine prenatal examination",
    location: "Room 205",
    price: 240,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-29"),
    updatedAt: new Date("2023-12-29"),
  },
  {
    id: "app24",
    patientId: "pat24",
    doctorId: "doc8",
    date: "2023-12-28",
    time: "10:00",
    type: "Psychiatry Consultation",
    status: "attended",
    title: "Depression Counseling",
    description: "Therapy session for depression",
    location: "Room 501",
    price: 320,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2023-12-28"),
  },
  {
    id: "app25",
    patientId: "pat25",
    doctorId: "doc9",
    date: "2023-12-27",
    time: "14:30",
    type: "Endocrinology Consultation",
    status: "attended",
    title: "Thyroid Function Test",
    description: "Thyroid hormone level assessment",
    location: "Room 302",
    price: 260,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-27"),
    updatedAt: new Date("2023-12-27"),
  },

  // Future appointments (next week)
  {
    id: "app26",
    patientId: "pat1",
    doctorId: "doc10",
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "09:00",
    type: "Pulmonology Consultation",
    status: "pending",
    title: "Asthma Follow-up",
    description: "Follow-up for asthma treatment",
    location: "Room 403",
    price: 270,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app27",
    patientId: "pat2",
    doctorId: "doc11",
    date: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "11:30",
    type: "Rheumatology Consultation",
    status: "pending",
    title: "Lupus Management",
    description: "Disease management and medication review",
    location: "Room 405",
    price: 290,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app28",
    patientId: "pat3",
    doctorId: "doc12",
    date: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "15:00",
    type: "Urology Consultation",
    status: "pending",
    title: "Kidney Stone Follow-up",
    description: "Post-treatment kidney stone assessment",
    location: "Room 301",
    price: 310,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app29",
    patientId: "pat4",
    doctorId: "doc13",
    date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "13:00",
    type: "Oncology Consultation",
    status: "pending",
    title: "Chemotherapy Session",
    description: "Scheduled chemotherapy treatment",
    location: "Room 601",
    price: 350,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app30",
    patientId: "pat5",
    doctorId: "doc14",
    date: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "10:30",
    type: "Ophthalmology Consultation",
    status: "pending",
    title: "Cataract Surgery Consultation",
    description: "Pre-surgery consultation for cataract removal",
    location: "Room 204",
    price: 230,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // More appointments to reach 100+
  {
    id: "app31",
    patientId: "pat6",
    doctorId: "doc15",
    date: "2023-12-26",
    time: "08:30",
    type: "Emergency Consultation",
    status: "attended",
    title: "Allergic Reaction",
    description: "Treatment for severe allergic reaction",
    location: "Emergency Room",
    price: 200,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-26"),
    updatedAt: new Date("2023-12-26"),
  },
  {
    id: "app32",
    patientId: "pat7",
    doctorId: "doc1",
    date: "2023-12-25",
    time: "14:00",
    type: "Cardiology Consultation",
    status: "attended",
    title: "Chest Pain Evaluation",
    description: "Assessment of chest discomfort",
    location: "Room 201",
    price: 250,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-25"),
    updatedAt: new Date("2023-12-25"),
  },
  {
    id: "app33",
    patientId: "pat8",
    doctorId: "doc2",
    date: "2023-12-24",
    time: "11:00",
    type: "Neurology Consultation",
    status: "attended",
    title: "Seizure Follow-up",
    description: "Post-seizure evaluation and medication adjustment",
    location: "Room 305",
    price: 300,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-24"),
    updatedAt: new Date("2023-12-24"),
  },
  {
    id: "app34",
    patientId: "pat9",
    doctorId: "doc3",
    date: "2023-12-23",
    time: "09:30",
    type: "Pediatric Consultation",
    status: "attended",
    title: "Growth Assessment",
    description: "Child growth and development check",
    location: "Room 102",
    price: 200,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-23"),
    updatedAt: new Date("2023-12-23"),
  },
  {
    id: "app35",
    patientId: "pat10",
    doctorId: "doc4",
    date: "2023-12-22",
    time: "16:00",
    type: "Orthopedic Consultation",
    status: "attended",
    title: "Hip Replacement Consultation",
    description: "Pre-surgery consultation for hip replacement",
    location: "Room 401",
    price: 275,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-22"),
    updatedAt: new Date("2023-12-22"),
  },

  // Continue with more appointments to reach 100+
  {
    id: "app36",
    patientId: "pat11",
    doctorId: "doc5",
    date: "2023-12-21",
    time: "12:30",
    type: "Dermatology Consultation",
    status: "attended",
    title: "Mole Examination",
    description: "Skin cancer screening and mole check",
    location: "Room 203",
    price: 225,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-21"),
    updatedAt: new Date("2023-12-21"),
  },
  {
    id: "app37",
    patientId: "pat12",
    doctorId: "doc6",
    date: "2023-12-20",
    time: "15:30",
    type: "Gastroenterology Consultation",
    status: "attended",
    title: "Colonoscopy Follow-up",
    description: "Post-colonoscopy results discussion",
    location: "Room 304",
    price: 280,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-20"),
    updatedAt: new Date("2023-12-20"),
  },
  {
    id: "app38",
    patientId: "pat13",
    doctorId: "doc7",
    date: "2023-12-19",
    time: "10:00",
    type: "Gynecology Consultation",
    status: "attended",
    title: "Menopause Consultation",
    description: "Hormone therapy discussion",
    location: "Room 205",
    price: 240,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-19"),
    updatedAt: new Date("2023-12-19"),
  },
  {
    id: "app39",
    patientId: "pat14",
    doctorId: "doc8",
    date: "2023-12-18",
    time: "13:30",
    type: "Psychiatry Consultation",
    status: "attended",
    title: "Anxiety Treatment",
    description: "Cognitive behavioral therapy session",
    location: "Room 501",
    price: 320,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-18"),
    updatedAt: new Date("2023-12-18"),
  },
  {
    id: "app40",
    patientId: "pat15",
    doctorId: "doc9",
    date: "2023-12-17",
    time: "11:30",
    type: "Endocrinology Consultation",
    status: "attended",
    title: "Insulin Adjustment",
    description: "Diabetes medication dosage adjustment",
    location: "Room 302",
    price: 260,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-17"),
    updatedAt: new Date("2023-12-17"),
  },

  // Adding more appointments to reach 100+ total
  {
    id: "app41",
    patientId: "pat16",
    doctorId: "doc10",
    date: "2023-12-16",
    time: "14:00",
    type: "Pulmonology Consultation",
    status: "attended",
    title: "COPD Management",
    description: "Chronic obstructive pulmonary disease treatment",
    location: "Room 403",
    price: 270,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-16"),
    updatedAt: new Date("2023-12-16"),
  },
  {
    id: "app42",
    patientId: "pat17",
    doctorId: "doc11",
    date: "2023-12-15",
    time: "09:00",
    type: "Rheumatology Consultation",
    status: "attended",
    title: "Fibromyalgia Treatment",
    description: "Pain management for fibromyalgia",
    location: "Room 405",
    price: 290,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-15"),
    updatedAt: new Date("2023-12-15"),
  },
  {
    id: "app43",
    patientId: "pat18",
    doctorId: "doc12",
    date: "2023-12-14",
    time: "16:30",
    type: "Urology Consultation",
    status: "attended",
    title: "Bladder Infection Treatment",
    description: "UTI treatment and prevention",
    location: "Room 301",
    price: 310,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-14"),
    updatedAt: new Date("2023-12-14"),
  },
  {
    id: "app44",
    patientId: "pat19",
    doctorId: "doc13",
    date: "2023-12-13",
    time: "12:00",
    type: "Oncology Consultation",
    status: "attended",
    title: "Radiation Therapy Planning",
    description: "Treatment planning for radiation therapy",
    location: "Room 601",
    price: 350,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-13"),
    updatedAt: new Date("2023-12-13"),
  },
  {
    id: "app45",
    patientId: "pat20",
    doctorId: "doc14",
    date: "2023-12-12",
    time: "08:30",
    type: "Ophthalmology Consultation",
    status: "attended",
    title: "Glaucoma Screening",
    description: "Eye pressure test and glaucoma assessment",
    location: "Room 204",
    price: 230,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-12"),
    updatedAt: new Date("2023-12-12"),
  },

  // Continue adding more appointments...
  {
    id: "app46",
    patientId: "pat21",
    doctorId: "doc15",
    date: "2023-12-11",
    time: "17:00",
    type: "Emergency Consultation",
    status: "attended",
    title: "Sports Injury",
    description: "Treatment for sports-related injury",
    location: "Emergency Room",
    price: 200,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-11"),
    updatedAt: new Date("2023-12-11"),
  },
  {
    id: "app47",
    patientId: "pat22",
    doctorId: "doc1",
    date: "2023-12-10",
    time: "10:30",
    type: "Cardiology Consultation",
    status: "attended",
    title: "Pacemaker Check",
    description: "Routine pacemaker function check",
    location: "Room 201",
    price: 250,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-10"),
    updatedAt: new Date("2023-12-10"),
  },
  {
    id: "app48",
    patientId: "pat23",
    doctorId: "doc2",
    date: "2023-12-09",
    time: "13:00",
    type: "Neurology Consultation",
    status: "attended",
    title: "Parkinson's Disease Management",
    description: "Medication adjustment for Parkinson's",
    location: "Room 305",
    price: 300,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-09"),
    updatedAt: new Date("2023-12-09"),
  },
  {
    id: "app49",
    patientId: "pat24",
    doctorId: "doc3",
    date: "2023-12-08",
    time: "15:30",
    type: "Pediatric Consultation",
    status: "attended",
    title: "ADHD Assessment",
    description: "Attention deficit hyperactivity disorder evaluation",
    location: "Room 102",
    price: 200,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-08"),
    updatedAt: new Date("2023-12-08"),
  },
  {
    id: "app50",
    patientId: "pat25",
    doctorId: "doc4",
    date: "2023-12-07",
    time: "11:00",
    type: "Orthopedic Consultation",
    status: "attended",
    title: "Physical Therapy Evaluation",
    description: "Post-surgery physical therapy assessment",
    location: "Room 401",
    price: 275,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-07"),
    updatedAt: new Date("2023-12-07"),
  },

  // Adding 50 more appointments to reach 100+
  {
    id: "app51",
    patientId: "pat1",
    doctorId: "doc5",
    date: "2023-12-06",
    time: "09:30",
    type: "Dermatology Consultation",
    status: "attended",
    title: "Eczema Treatment",
    description: "Topical treatment for eczema",
    location: "Room 203",
    price: 225,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-06"),
    updatedAt: new Date("2023-12-06"),
  },
  {
    id: "app52",
    patientId: "pat2",
    doctorId: "doc6",
    date: "2023-12-05",
    time: "14:30",
    type: "Gastroenterology Consultation",
    status: "attended",
    title: "IBS Management",
    description: "Irritable bowel syndrome treatment plan",
    location: "Room 304",
    price: 280,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-05"),
    updatedAt: new Date("2023-12-05"),
  },
  {
    id: "app53",
    patientId: "pat3",
    doctorId: "doc7",
    date: "2023-12-04",
    time: "16:00",
    type: "Gynecology Consultation",
    status: "attended",
    title: "Birth Control Consultation",
    description: "Contraceptive options discussion",
    location: "Room 205",
    price: 240,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-04"),
    updatedAt: new Date("2023-12-04"),
  },
  {
    id: "app54",
    patientId: "pat4",
    doctorId: "doc8",
    date: "2023-12-03",
    time: "10:00",
    type: "Psychiatry Consultation",
    status: "attended",
    title: "Bipolar Disorder Treatment",
    description: "Mood stabilizer medication review",
    location: "Room 501",
    price: 320,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-03"),
    updatedAt: new Date("2023-12-03"),
  },
  {
    id: "app55",
    patientId: "pat5",
    doctorId: "doc9",
    date: "2023-12-02",
    time: "12:30",
    type: "Endocrinology Consultation",
    status: "attended",
    title: "Hormone Replacement Therapy",
    description: "HRT consultation and monitoring",
    location: "Room 302",
    price: 260,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-02"),
    updatedAt: new Date("2023-12-02"),
  },

  // Continue with more appointments...
  {
    id: "app56",
    patientId: "pat6",
    doctorId: "doc10",
    date: "2023-12-01",
    time: "08:00",
    type: "Pulmonology Consultation",
    status: "attended",
    title: "Sleep Study Results",
    description: "Sleep apnea study results review",
    location: "Room 403",
    price: 270,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date("2023-12-01"),
  },
  {
    id: "app57",
    patientId: "pat7",
    doctorId: "doc11",
    date: "2023-11-30",
    time: "15:00",
    type: "Rheumatology Consultation",
    status: "attended",
    title: "Gout Treatment",
    description: "Uric acid level management",
    location: "Room 405",
    price: 290,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-30"),
    updatedAt: new Date("2023-11-30"),
  },
  {
    id: "app58",
    patientId: "pat8",
    doctorId: "doc12",
    date: "2023-11-29",
    time: "11:30",
    type: "Urology Consultation",
    status: "attended",
    title: "Erectile Dysfunction Treatment",
    description: "ED treatment options discussion",
    location: "Room 301",
    price: 310,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-29"),
    updatedAt: new Date("2023-11-29"),
  },
  {
    id: "app59",
    patientId: "pat9",
    doctorId: "doc13",
    date: "2023-11-28",
    time: "13:30",
    type: "Oncology Consultation",
    status: "attended",
    title: "Immunotherapy Session",
    description: "Cancer immunotherapy treatment",
    location: "Room 601",
    price: 350,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-28"),
    updatedAt: new Date("2023-11-28"),
  },
  {
    id: "app60",
    patientId: "pat10",
    doctorId: "doc14",
    date: "2023-11-27",
    time: "09:00",
    type: "Ophthalmology Consultation",
    status: "attended",
    title: "Diabetic Retinopathy Screening",
    description: "Eye examination for diabetes complications",
    location: "Room 204",
    price: 230,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-27"),
    updatedAt: new Date("2023-11-27"),
  },

  // Adding more future appointments
  {
    id: "app61",
    patientId: "pat11",
    doctorId: "doc1",
    date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "10:00",
    type: "Cardiology Consultation",
    status: "pending",
    title: "Stress Test",
    description: "Cardiac stress test evaluation",
    location: "Room 201",
    price: 250,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app62",
    patientId: "pat12",
    doctorId: "doc2",
    date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "14:00",
    type: "Neurology Consultation",
    status: "pending",
    title: "MRI Results Review",
    description: "Brain MRI results discussion",
    location: "Room 305",
    price: 300,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app63",
    patientId: "pat13",
    doctorId: "doc3",
    date: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "11:30",
    type: "Pediatric Consultation",
    status: "pending",
    title: "School Physical",
    description: "Required school physical examination",
    location: "Room 102",
    price: 200,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app64",
    patientId: "pat14",
    doctorId: "doc4",
    date: new Date(Date.now() + 17 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "15:30",
    type: "Orthopedic Consultation",
    status: "pending",
    title: "Shoulder Surgery Follow-up",
    description: "Post-operative shoulder assessment",
    location: "Room 401",
    price: 275,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app65",
    patientId: "pat15",
    doctorId: "doc5",
    date: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "09:30",
    type: "Dermatology Consultation",
    status: "pending",
    title: "Skin Biopsy Results",
    description: "Biopsy results review and treatment plan",
    location: "Room 203",
    price: 225,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Continue adding more appointments to reach 100+
  {
    id: "app66",
    patientId: "pat16",
    doctorId: "doc6",
    date: new Date(Date.now() + 19 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "13:00",
    type: "Gastroenterology Consultation",
    status: "pending",
    title: "Endoscopy Procedure",
    description: "Upper endoscopy examination",
    location: "Room 304",
    price: 280,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app67",
    patientId: "pat17",
    doctorId: "doc7",
    date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "16:00",
    type: "Gynecology Consultation",
    status: "pending",
    title: "Fertility Consultation",
    description: "Fertility assessment and treatment options",
    location: "Room 205",
    price: 240,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app68",
    patientId: "pat18",
    doctorId: "doc8",
    date: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "10:30",
    type: "Psychiatry Consultation",
    status: "pending",
    title: "PTSD Treatment",
    description: "Post-traumatic stress disorder therapy",
    location: "Room 501",
    price: 320,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app69",
    patientId: "pat19",
    doctorId: "doc9",
    date: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "12:00",
    type: "Endocrinology Consultation",
    status: "pending",
    title: "Adrenal Function Test",
    description: "Adrenal gland function assessment",
    location: "Room 302",
    price: 260,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "app70",
    patientId: "pat20",
    doctorId: "doc10",
    date: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    time: "14:30",
    type: "Pulmonology Consultation",
    status: "pending",
    title: "Lung Transplant Evaluation",
    description: "Pre-transplant lung function assessment",
    location: "Room 403",
    price: 270,
    isActiveWithDoctor: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Adding more past appointments
  {
    id: "app71",
    patientId: "pat21",
    doctorId: "doc11",
    date: "2023-11-26",
    time: "08:30",
    type: "Rheumatology Consultation",
    status: "attended",
    title: "Rheumatoid Arthritis Treatment",
    description: "Disease-modifying antirheumatic drugs review",
    location: "Room 405",
    price: 290,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-26"),
    updatedAt: new Date("2023-11-26"),
  },
  {
    id: "app72",
    patientId: "pat22",
    doctorId: "doc12",
    date: "2023-11-25",
    time: "17:00",
    type: "Urology Consultation",
    status: "attended",
    title: "Vasectomy Consultation",
    description: "Pre-procedure vasectomy consultation",
    location: "Room 301",
    price: 310,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-25"),
    updatedAt: new Date("2023-11-25"),
  },
  {
    id: "app73",
    patientId: "pat23",
    doctorId: "doc13",
    date: "2023-11-24",
    time: "11:00",
    type: "Oncology Consultation",
    status: "attended",
    title: "Tumor Marker Test",
    description: "Blood test for cancer markers",
    location: "Room 601",
    price: 350,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-24"),
    updatedAt: new Date("2023-11-24"),
  },
  {
    id: "app74",
    patientId: "pat24",
    doctorId: "doc14",
    date: "2023-11-23",
    time: "15:00",
    type: "Ophthalmology Consultation",
    status: "attended",
    title: "Retinal Detachment Surgery",
    description: "Emergency retinal reattachment procedure",
    location: "Room 204",
    price: 230,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-23"),
    updatedAt: new Date("2023-11-23"),
  },
  {
    id: "app75",
    patientId: "pat25",
    doctorId: "doc15",
    date: "2023-11-22",
    time: "12:30",
    type: "Emergency Consultation",
    status: "attended",
    title: "Broken Bone Treatment",
    description: "Fracture treatment and casting",
    location: "Emergency Room",
    price: 200,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-22"),
    updatedAt: new Date("2023-11-22"),
  },

  // Adding final appointments to reach 100+
  {
    id: "app76",
    patientId: "pat1",
    doctorId: "doc1",
    date: "2023-11-21",
    time: "09:00",
    type: "Cardiology Consultation",
    status: "attended",
    title: "Holter Monitor Results",
    description: "24-hour heart rhythm monitoring results",
    location: "Room 201",
    price: 250,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-21"),
    updatedAt: new Date("2023-11-21"),
  },
  {
    id: "app77",
    patientId: "pat2",
    doctorId: "doc2",
    date: "2023-11-20",
    time: "13:30",
    type: "Neurology Consultation",
    status: "attended",
    title: "Multiple Sclerosis Treatment",
    description: "MS disease management and medication",
    location: "Room 305",
    price: 300,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-20"),
    updatedAt: new Date("2023-11-20"),
  },
  {
    id: "app78",
    patientId: "pat3",
    doctorId: "doc3",
    date: "2023-11-19",
    time: "16:30",
    type: "Pediatric Consultation",
    status: "attended",
    title: "Autism Spectrum Evaluation",
    description: "Developmental assessment for autism",
    location: "Room 102",
    price: 200,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-19"),
    updatedAt: new Date("2023-11-19"),
  },
  {
    id: "app79",
    patientId: "pat4",
    doctorId: "doc4",
    date: "2023-11-18",
    time: "10:00",
    type: "Orthopedic Consultation",
    status: "attended",
    title: "Spinal Fusion Follow-up",
    description: "Post-surgery spinal assessment",
    location: "Room 401",
    price: 275,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-18"),
    updatedAt: new Date("2023-11-18"),
  },
  {
    id: "app80",
    patientId: "pat5",
    doctorId: "doc5",
    date: "2023-11-17",
    time: "14:00",
    type: "Dermatology Consultation",
    status: "attended",
    title: "Laser Treatment Session",
    description: "Laser therapy for skin condition",
    location: "Room 203",
    price: 225,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-17"),
    updatedAt: new Date("2023-11-17"),
  },

  // Continue with more appointments...
  {
    id: "app81",
    patientId: "pat6",
    doctorId: "doc6",
    date: "2023-11-16",
    time: "11:30",
    type: "Gastroenterology Consultation",
    status: "attended",
    title: "Liver Function Test",
    description: "Hepatic function assessment",
    location: "Room 304",
    price: 280,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-16"),
    updatedAt: new Date("2023-11-16"),
  },
  {
    id: "app82",
    patientId: "pat7",
    doctorId: "doc7",
    date: "2023-11-15",
    time: "08:00",
    type: "Gynecology Consultation",
    status: "attended",
    title: "Hysterectomy Consultation",
    description: "Pre-surgical hysterectomy discussion",
    location: "Room 205",
    price: 240,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-15"),
    updatedAt: new Date("2023-11-15"),
  },
  {
    id: "app83",
    patientId: "pat8",
    doctorId: "doc8",
    date: "2023-11-14",
    time: "15:30",
    type: "Psychiatry Consultation",
    status: "attended",
    title: "Medication Management",
    description: "Psychiatric medication review and adjustment",
    location: "Room 501",
    price: 320,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-14"),
    updatedAt: new Date("2023-11-14"),
  },
  {
    id: "app84",
    patientId: "pat9",
    doctorId: "doc9",
    date: "2023-11-13",
    time: "12:00",
    type: "Endocrinology Consultation",
    status: "attended",
    title: "Pituitary Gland Assessment",
    description: "Hormone production evaluation",
    location: "Room 302",
    price: 260,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-13"),
    updatedAt: new Date("2023-11-13"),
  },
  {
    id: "app85",
    patientId: "pat10",
    doctorId: "doc10",
    date: "2023-11-12",
    time: "09:30",
    type: "Pulmonology Consultation",
    status: "attended",
    title: "Bronchoscopy Procedure",
    description: "Lung examination via bronchoscopy",
    location: "Room 403",
    price: 270,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-12"),
    updatedAt: new Date("2023-11-12"),
  },

  // Final set of appointments to exceed 100
  {
    id: "app86",
    patientId: "pat11",
    doctorId: "doc11",
    date: "2023-11-11",
    time: "16:00",
    type: "Rheumatology Consultation",
    status: "attended",
    title: "Psoriatic Arthritis Treatment",
    description: "Biologic therapy for psoriatic arthritis",
    location: "Room 405",
    price: 290,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-11"),
    updatedAt: new Date("2023-11-11"),
  },
  {
    id: "app87",
    patientId: "pat12",
    doctorId: "doc12",
    date: "2023-11-10",
    time: "13:00",
    type: "Urology Consultation",
    status: "attended",
    title: "Prostate Biopsy Results",
    description: "Biopsy results review and treatment plan",
    location: "Room 301",
    price: 310,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2023-11-10"),
  },
  {
    id: "app88",
    patientId: "pat13",
    doctorId: "doc13",
    date: "2023-11-09",
    time: "10:30",
    type: "Oncology Consultation",
    status: "attended",
    title: "Bone Marrow Transplant Consultation",
    description: "Pre-transplant evaluation and planning",
    location: "Room 601",
    price: 350,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-09"),
    updatedAt: new Date("2023-11-09"),
  },
  {
    id: "app89",
    patientId: "pat14",
    doctorId: "doc14",
    date: "2023-11-08",
    time: "14:30",
    type: "Ophthalmology Consultation",
    status: "attended",
    title: "Corneal Transplant Follow-up",
    description: "Post-transplant corneal assessment",
    location: "Room 204",
    price: 230,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-08"),
    updatedAt: new Date("2023-11-08"),
  },
  {
    id: "app90",
    patientId: "pat15",
    doctorId: "doc15",
    date: "2023-11-07",
    time: "17:30",
    type: "Emergency Consultation",
    status: "attended",
    title: "Cardiac Arrest Response",
    description: "Emergency cardiac resuscitation",
    location: "Emergency Room",
    price: 200,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-07"),
    updatedAt: new Date("2023-11-07"),
  },

  // Adding 10 more to exceed 100 appointments
  {
    id: "app91",
    patientId: "pat16",
    doctorId: "doc1",
    date: "2023-11-06",
    time: "08:30",
    type: "Cardiology Consultation",
    status: "attended",
    title: "Angioplasty Follow-up",
    description: "Post-angioplasty cardiac assessment",
    location: "Room 201",
    price: 250,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-06"),
    updatedAt: new Date("2023-11-06"),
  },
  {
    id: "app92",
    patientId: "pat17",
    doctorId: "doc2",
    date: "2023-11-05",
    time: "11:00",
    type: "Neurology Consultation",
    status: "attended",
    title: "Stroke Recovery Assessment",
    description: "Post-stroke rehabilitation evaluation",
    location: "Room 305",
    price: 300,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-05"),
    updatedAt: new Date("2023-11-05"),
  },
  {
    id: "app93",
    patientId: "pat18",
    doctorId: "doc3",
    date: "2023-11-04",
    time: "15:00",
    type: "Pediatric Consultation",
    status: "attended",
    title: "Developmental Delay Assessment",
    description: "Child development milestone evaluation",
    location: "Room 102",
    price: 200,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-04"),
    updatedAt: new Date("2023-11-04"),
  },
  {
    id: "app94",
    patientId: "pat19",
    doctorId: "doc4",
    date: "2023-11-03",
    time: "12:30",
    type: "Orthopedic Consultation",
    status: "attended",
    title: "Joint Replacement Consultation",
    description: "Pre-surgical joint replacement planning",
    location: "Room 401",
    price: 275,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-03"),
    updatedAt: new Date("2023-11-03"),
  },
  {
    id: "app95",
    patientId: "pat20",
    doctorId: "doc5",
    date: "2023-11-02",
    time: "09:00",
    type: "Dermatology Consultation",
    status: "attended",
    title: "Melanoma Screening",
    description: "Comprehensive skin cancer screening",
    location: "Room 203",
    price: 225,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-02"),
    updatedAt: new Date("2023-11-02"),
  },
  {
    id: "app96",
    patientId: "pat21",
    doctorId: "doc6",
    date: "2023-11-01",
    time: "16:30",
    type: "Gastroenterology Consultation",
    status: "attended",
    title: "Crohn's Disease Management",
    description: "Inflammatory bowel disease treatment",
    location: "Room 304",
    price: 280,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-11-01"),
    updatedAt: new Date("2023-11-01"),
  },
  {
    id: "app97",
    patientId: "pat22",
    doctorId: "doc7",
    date: "2023-10-31",
    time: "13:30",
    type: "Gynecology Consultation",
    status: "attended",
    title: "Ovarian Cyst Removal",
    description: "Laparoscopic ovarian cyst removal",
    location: "Room 205",
    price: 240,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-10-31"),
    updatedAt: new Date("2023-10-31"),
  },
  {
    id: "app98",
    patientId: "pat23",
    doctorId: "doc8",
    date: "2023-10-30",
    time: "10:00",
    type: "Psychiatry Consultation",
    status: "attended",
    title: "Eating Disorder Treatment",
    description: "Comprehensive eating disorder therapy",
    location: "Room 501",
    price: 320,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-10-30"),
    updatedAt: new Date("2023-10-30"),
  },
  {
    id: "app99",
    patientId: "pat24",
    doctorId: "doc9",
    date: "2023-10-29",
    time: "14:00",
    type: "Endocrinology Consultation",
    status: "attended",
    title: "Growth Hormone Therapy",
    description: "Pediatric growth hormone treatment",
    location: "Room 302",
    price: 260,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-10-29"),
    updatedAt: new Date("2023-10-29"),
  },
  {
    id: "app100",
    patientId: "pat25",
    doctorId: "doc10",
    date: "2023-10-28",
    time: "11:30",
    type: "Pulmonology Consultation",
    status: "attended",
    title: "Lung Cancer Screening",
    description: "CT scan for lung cancer detection",
    location: "Room 403",
    price: 270,
    isActiveWithDoctor: false,
    createdAt: new Date("2023-10-28"),
    updatedAt: new Date("2023-10-28"),
  },
]

// Keep existing admin, appointment details, documents, notifications, reschedule requests, and enquiries data
export const admins: Admin[] = [
  {
    id: "admin1",
    email: "admin@afc.com",
    name: "Admin User",
    role: "admin",
    phone: "(555) 345-6789",
    department: "Administration",
    permissions: ["all"],
    createdAt: new Date("2020-01-01"),
    updatedAt: new Date("2023-12-10"),
  },
]

export const appointmentDetails: AppointmentDetails[] = [
  {
    id: "detail1",
    appointmentId: "app1",
    symptoms: ["Chest pain", "Shortness of breath"],
    diagnosis: "Angina",
    prescription: ["Nitroglycerin", "Aspirin"],
    notes: "Patient experiencing mild chest discomfort. Recommended lifestyle changes.",
    followUpDate: "2024-02-15",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "detail2",
    appointmentId: "app2",
    symptoms: ["Severe headache", "Nausea"],
    diagnosis: "Migraine",
    prescription: ["Sumatriptan", "Ibuprofen"],
    notes: "Chronic migraine pattern. Discussed trigger avoidance strategies.",
    followUpDate: "2024-02-20",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const documents: Document[] = [
  {
    id: "doc1",
    patientId: "pat1",
    name: "Lab Results - Blood Work",
    type: "lab_result",
    url: "/documents/lab-results-pat1.pdf",
    uploadedBy: "doc1",
    uploadedAt: new Date("2024-01-10"),
  },
  {
    id: "doc2",
    patientId: "pat2",
    name: "MRI Scan - Brain",
    type: "imaging",
    url: "/documents/mri-brain-pat2.pdf",
    uploadedBy: "doc2",
    uploadedAt: new Date("2024-01-08"),
  },
]

export const notifications: Notification[] = [
  {
    id: "notif1",
    userId: "pat1",
    title: "Appointment Reminder",
    message: "Your cardiology appointment is tomorrow at 9:00 AM",
    type: "appointment",
    read: false,
    createdAt: new Date(),
  },
  {
    id: "notif2",
    userId: "doc1",
    title: "New Patient Assigned",
    message: "You have been assigned a new patient: John Patient",
    type: "assignment",
    read: false,
    createdAt: new Date(),
  },
]

export const rescheduleRequests: RescheduleRequest[] = [
  {
    id: "req1",
    appointmentId: "app1",
    requestedBy: "pat1",
    currentDate: new Date().toISOString().split("T")[0],
    currentTime: "09:00",
    requestedDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    requestedTime: "14:00",
    reason: "Work conflict",
    status: "pending",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "req2",
    appointmentId: "app3",
    requestedBy: "pat3",
    currentDate: new Date().toISOString().split("T")[0],
    currentTime: "11:00",
    requestedDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    requestedTime: "15:00",
    reason: "Family emergency",
    status: "pending",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "req3",
    appointmentId: "app5",
    requestedBy: "pat5",
    currentDate: new Date().toISOString().split("T")[0],
    currentTime: "15:30",
    requestedDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    requestedTime: "10:00",
    reason: "Medical procedure conflict",
    status: "pending",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const enquiries: Enquiry[] = [
  {
    id: "enq1",
    patientId: "pat1",
    subject: "Billing Question",
    message: "I have a question about my recent bill for the cardiology consultation.",
    category: "billing",
    status: "pending",
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "enq2",
    patientId: "pat2",
    subject: "Appointment Scheduling",
    message: "I need to schedule a follow-up appointment for my migraine treatment.",
    category: "appointment",
    status: "pending",
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
